name = "Steam Deck Battery Usage Crankshaft Plugin"
version = "0.1"
link = "https://github.com/Random90/steam-deck-battery-usage-plugin"
source = "https://github.com/Random90/steam-deck-battery-usage-plugin"
min-crankshaft-version = "0.2.4"

[author]
name = "Grzegorz Czernatowicz"
link = "https://github.com/Random90"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = false

	[entrypoints.deck]
	library = true
	menu = false
	quick-access = false

[store]
description = """
Better battery stats for steam deck.
Monitors battery usage since last charging. 
"""